spring:
  profiles:
    include: secret
    active: dev
  application:
    name: practice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql=true
        show-sql:true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG